import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google"
import StoreProvider from "./StoreProvider";
const nunito = Nunito({ subsets: ["vietnamese"], weight: ["400", "900"] })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className}`}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
