import { AsideFragment } from "@/components/AsideFagment";
import PrivateElement from "@/components/element/PrivateElement";
import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex mx-auto" style={{ width: "1440px", height: "810px" }}>
            <PrivateElement>
                <AsideFragment />
                <div className="bg-[#F6F6F6] grow pl-6">
                    {children}
                </div>
            </PrivateElement>
        </div>
    );
}
